import type { ThemeDefinition } from './types';

const catppuccinLatte: ThemeDefinition = {
  id: 'catppuccin-latte',
  name: 'Catppuccin Latte',
  type: 'light',
  colors: {
    'bg-primary': '#ffffff',
    'bg-secondary': '#f5f5f5',
    'bg-tertiary': '#e8e8e8',
    'bg-surface': '#e6e9ef',
    'text-primary': '#1e1e2e',
    'text-secondary': '#585b70',
    'text-tertiary': '#9ca0b0',
    accent: '#1e66f5',
    'accent-hover': '#2a7ae8',
    border: '#dce0e8',
    danger: '#d20f39',
    success: '#40a02b',
    warning: '#df8e1d',
    'scrollbar-track': '#f5f5f5',
    'scrollbar-thumb': '#dce0e8',
    'scrollbar-thumb-hover': '#bcc0cc',
  },
  tokenRules: [
    { token: '', foreground: '1e1e2e' },
    { token: 'string', foreground: '40a02b' },
    { token: 'number', foreground: 'fe640b' },
    { token: 'keyword', foreground: '1e66f5' },
    { token: 'delimiter', foreground: '9ca0b0' },
    { token: 'comment', foreground: '8c8fa1', fontStyle: 'italic' },
    { token: 'string.key.json', foreground: '1e66f5' },
    { token: 'string.value.json', foreground: '40a02b' },
    { token: 'number.json', foreground: 'fe640b' },
    { token: 'keyword.json', foreground: 'd20f39' },
  ],
  editorColors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#1e1e2e',
    'editor.lineHighlightBackground': '#dce0e833',
    'editor.selectionBackground': '#1e66f533',
    'editorCursor.foreground': '#1e66f5',
    'editorLineNumber.foreground': '#9ca0b0',
    'editorLineNumber.activeForeground': '#585b70',
    'editor.inactiveSelectionBackground': '#1e66f51a',
    'editorIndentGuide.background': '#dce0e866',
    'editorWidget.background': '#f5f5f5',
    'editorWidget.border': '#dce0e8',
    'input.background': '#ffffff',
    'input.foreground': '#1e1e2e',
    'input.border': '#dce0e8',
    'scrollbarSlider.background': '#dce0e866',
    'scrollbarSlider.hoverBackground': '#dce0e899',
    'scrollbarSlider.activeBackground': '#dce0e8cc',
  },
};

export default catppuccinLatte;
