import type { ThemeDefinition } from './types';

const catppuccinMocha: ThemeDefinition = {
  id: 'catppuccin-mocha',
  name: 'Catppuccin Mocha',
  type: 'dark',
  colors: {
    'bg-primary': '#1e1e2e',
    'bg-secondary': '#181825',
    'bg-tertiary': '#11111b',
    'bg-surface': '#313244',
    'text-primary': '#cdd6f4',
    'text-secondary': '#a6adc8',
    'text-tertiary': '#585b70',
    accent: '#89b4fa',
    'accent-hover': '#74c7ec',
    border: '#313244',
    danger: '#f38ba8',
    success: '#a6e3a1',
    warning: '#fab387',
    'scrollbar-track': '#1e1e2e',
    'scrollbar-thumb': '#313244',
    'scrollbar-thumb-hover': '#45475a',
  },
  tokenRules: [
    { token: '', foreground: 'cdd6f4' },
    { token: 'string', foreground: 'a6e3a1' },
    { token: 'number', foreground: 'fab387' },
    { token: 'keyword', foreground: '89b4fa' },
    { token: 'delimiter', foreground: '585b70' },
    { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'string.key.json', foreground: '89b4fa' },
    { token: 'string.value.json', foreground: 'a6e3a1' },
    { token: 'number.json', foreground: 'fab387' },
    { token: 'keyword.json', foreground: 'f38ba8' },
  ],
  editorColors: {
    'editor.background': '#1e1e2e',
    'editor.foreground': '#cdd6f4',
    'editor.lineHighlightBackground': '#31324433',
    'editor.selectionBackground': '#89b4fa33',
    'editorCursor.foreground': '#89b4fa',
    'editorLineNumber.foreground': '#585b70',
    'editorLineNumber.activeForeground': '#a6adc8',
    'editor.inactiveSelectionBackground': '#89b4fa1a',
    'editorIndentGuide.background': '#31324466',
    'editorWidget.background': '#181825',
    'editorWidget.border': '#313244',
    'input.background': '#313244',
    'input.foreground': '#cdd6f4',
    'input.border': '#313244',
    'scrollbarSlider.background': '#31324466',
    'scrollbarSlider.hoverBackground': '#31324499',
    'scrollbarSlider.activeBackground': '#313244cc',
  },
};

export default catppuccinMocha;
