import type { ThemeDefinition } from './types';

const cursorDark: ThemeDefinition = {
  id: 'cursor-dark',
  name: 'Cursor Dark',
  type: 'dark',
  colors: {
    'bg-primary': '#1a1a1a',
    'bg-secondary': '#141414',
    'bg-tertiary': '#0f0f0f',
    'bg-surface': '#2a2a2a',
    'text-primary': '#d6d6dd',
    'text-secondary': '#a0a0a8',
    'text-tertiary': '#6d6d6d',
    accent: '#4c9df3',
    'accent-hover': '#6bb0f7',
    border: '#2a2a2a',
    danger: '#bf616a',
    success: '#a8cc7c',
    warning: '#ebc88d',
    'scrollbar-track': '#1a1a1a',
    'scrollbar-thumb': '#40404055',
    'scrollbar-thumb-hover': '#60606055',
  },
  tokenRules: [
    { token: '', foreground: 'd6d6dd' },
    { token: 'string', foreground: 'a8cc7c' },
    { token: 'number', foreground: 'ebc88d' },
    { token: 'keyword', foreground: '83d6c5' },
    { token: 'delimiter', foreground: '6d6d6d' },
    { token: 'comment', foreground: '6d6d6d', fontStyle: 'italic' },
    { token: 'type', foreground: 'efb080' },
    { token: 'string.key.json', foreground: 'aaa0fa' },
    { token: 'string.value.json', foreground: 'a8cc7c' },
    { token: 'number.json', foreground: 'ebc88d' },
    { token: 'keyword.json', foreground: '82d2ce' },
  ],
  editorColors: {
    'editor.background': '#1a1a1a',
    'editor.foreground': '#d6d6dd',
    'editor.lineHighlightBackground': '#29292955',
    'editor.selectionBackground': '#40404099',
    'editorCursor.foreground': '#ffffff',
    'editorLineNumber.foreground': '#505050',
    'editorLineNumber.activeForeground': '#ffffff',
    'editor.inactiveSelectionBackground': '#40404055',
    'editorIndentGuide.background': '#2a2a2a',
    'editorWidget.background': '#141414',
    'editorWidget.border': '#2a2a2a',
    'input.background': '#2a2a2a',
    'input.foreground': '#ffffff',
    'input.border': '#2a2a2a',
    'scrollbarSlider.background': '#40404055',
    'scrollbarSlider.hoverBackground': '#40404099',
    'scrollbarSlider.activeBackground': '#606060cc',
  },
};

export default cursorDark;
