import type { ThemeDefinition } from './types';

const dracula: ThemeDefinition = {
  id: 'dracula',
  name: 'Dracula',
  type: 'dark',
  colors: {
    'bg-primary': '#282a36',
    'bg-secondary': '#21222c',
    'bg-tertiary': '#191a21',
    'bg-surface': '#44475a',
    'text-primary': '#f8f8f2',
    'text-secondary': '#bfbfbf',
    'text-tertiary': '#6272a4',
    accent: '#bd93f9',
    'accent-hover': '#ff79c6',
    border: '#44475a',
    danger: '#ff5555',
    success: '#50fa7b',
    warning: '#ffb86c',
    'scrollbar-track': '#282a36',
    'scrollbar-thumb': '#44475a',
    'scrollbar-thumb-hover': '#6272a4',
  },
  tokenRules: [
    { token: '', foreground: 'f8f8f2' },
    { token: 'string', foreground: 'f1fa8c' },
    { token: 'number', foreground: 'bd93f9' },
    { token: 'keyword', foreground: 'ff79c6' },
    { token: 'delimiter', foreground: '6272a4' },
    { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
    { token: 'type', foreground: '8be9fd' },
    { token: 'string.key.json', foreground: '8be9fd' },
    { token: 'string.value.json', foreground: 'f1fa8c' },
    { token: 'number.json', foreground: 'bd93f9' },
    { token: 'keyword.json', foreground: 'ff79c6' },
  ],
  editorColors: {
    'editor.background': '#282a36',
    'editor.foreground': '#f8f8f2',
    'editor.lineHighlightBackground': '#44475a33',
    'editor.selectionBackground': '#44475a',
    'editorCursor.foreground': '#f8f8f2',
    'editorLineNumber.foreground': '#6272a4',
    'editorLineNumber.activeForeground': '#f8f8f2',
    'editor.inactiveSelectionBackground': '#44475a33',
    'editorIndentGuide.background': '#44475a66',
    'editorWidget.background': '#21222c',
    'editorWidget.border': '#44475a',
    'input.background': '#44475a',
    'input.foreground': '#f8f8f2',
    'input.border': '#44475a',
    'scrollbarSlider.background': '#44475a66',
    'scrollbarSlider.hoverBackground': '#44475a99',
    'scrollbarSlider.activeBackground': '#44475acc',
  },
};

export default dracula;
