import type { ThemeDefinition } from './types';

const githubLight: ThemeDefinition = {
  id: 'github-light',
  name: 'GitHub Light',
  type: 'light',
  colors: {
    'bg-primary': '#ffffff',
    'bg-secondary': '#f6f8fa',
    'bg-tertiary': '#eaeef2',
    'bg-surface': '#f0f3f6',
    'text-primary': '#1f2328',
    'text-secondary': '#656d76',
    'text-tertiary': '#8b949e',
    accent: '#0969da',
    'accent-hover': '#0550ae',
    border: '#d0d7de',
    danger: '#cf222e',
    success: '#1a7f37',
    warning: '#9a6700',
    'scrollbar-track': '#f6f8fa',
    'scrollbar-thumb': '#d0d7de',
    'scrollbar-thumb-hover': '#afb8c1',
  },
  tokenRules: [
    { token: '', foreground: '1f2328' },
    { token: 'string', foreground: '0a3069' },
    { token: 'number', foreground: '0550ae' },
    { token: 'keyword', foreground: 'cf222e' },
    { token: 'delimiter', foreground: '8b949e' },
    { token: 'comment', foreground: '6e7781', fontStyle: 'italic' },
    { token: 'type', foreground: '8250df' },
    { token: 'string.key.json', foreground: '0550ae' },
    { token: 'string.value.json', foreground: '0a3069' },
    { token: 'number.json', foreground: '0550ae' },
    { token: 'keyword.json', foreground: 'cf222e' },
  ],
  editorColors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#1f2328',
    'editor.lineHighlightBackground': '#f6f8fa',
    'editor.selectionBackground': '#0969da33',
    'editorCursor.foreground': '#0969da',
    'editorLineNumber.foreground': '#8b949e',
    'editorLineNumber.activeForeground': '#1f2328',
    'editor.inactiveSelectionBackground': '#0969da1a',
    'editorIndentGuide.background': '#d0d7de66',
    'editorWidget.background': '#f6f8fa',
    'editorWidget.border': '#d0d7de',
    'input.background': '#ffffff',
    'input.foreground': '#1f2328',
    'input.border': '#d0d7de',
    'scrollbarSlider.background': '#d0d7de66',
    'scrollbarSlider.hoverBackground': '#d0d7de99',
    'scrollbarSlider.activeBackground': '#d0d7decc',
  },
};

export default githubLight;
