import type { ThemeDefinition } from './types';

const nord: ThemeDefinition = {
  id: 'nord',
  name: 'Nord',
  type: 'dark',
  colors: {
    'bg-primary': '#2e3440',
    'bg-secondary': '#3b4252',
    'bg-tertiary': '#2e3440',
    'bg-surface': '#434c5e',
    'text-primary': '#d8dee9',
    'text-secondary': '#9eaab8',
    'text-tertiary': '#4c566a',
    accent: '#88c0d0',
    'accent-hover': '#81a1c1',
    border: '#3b4252',
    danger: '#bf616a',
    success: '#a3be8c',
    warning: '#ebcb8b',
    'scrollbar-track': '#2e3440',
    'scrollbar-thumb': '#434c5e',
    'scrollbar-thumb-hover': '#4c566a',
  },
  tokenRules: [
    { token: '', foreground: 'd8dee9' },
    { token: 'string', foreground: 'a3be8c' },
    { token: 'number', foreground: 'b48ead' },
    { token: 'keyword', foreground: '81a1c1' },
    { token: 'delimiter', foreground: '4c566a' },
    { token: 'comment', foreground: '616e88', fontStyle: 'italic' },
    { token: 'type', foreground: '8fbcbb' },
    { token: 'string.key.json', foreground: '8fbcbb' },
    { token: 'string.value.json', foreground: 'a3be8c' },
    { token: 'number.json', foreground: 'b48ead' },
    { token: 'keyword.json', foreground: '81a1c1' },
  ],
  editorColors: {
    'editor.background': '#2e3440',
    'editor.foreground': '#d8dee9',
    'editor.lineHighlightBackground': '#3b425233',
    'editor.selectionBackground': '#434c5ecc',
    'editorCursor.foreground': '#d8dee9',
    'editorLineNumber.foreground': '#4c566a',
    'editorLineNumber.activeForeground': '#d8dee9',
    'editor.inactiveSelectionBackground': '#434c5e33',
    'editorIndentGuide.background': '#3b425266',
    'editorWidget.background': '#3b4252',
    'editorWidget.border': '#3b4252',
    'input.background': '#434c5e',
    'input.foreground': '#d8dee9',
    'input.border': '#3b4252',
    'scrollbarSlider.background': '#434c5e66',
    'scrollbarSlider.hoverBackground': '#434c5e99',
    'scrollbarSlider.activeBackground': '#434c5ecc',
  },
};

export default nord;
