import type { ThemeDefinition } from './types';

const oneLight: ThemeDefinition = {
  id: 'one-light',
  name: 'One Light',
  type: 'light',
  colors: {
    'bg-primary': '#fafafa',
    'bg-secondary': '#f0f0f0',
    'bg-tertiary': '#e5e5e6',
    'bg-surface': '#eaeaeb',
    'text-primary': '#383a42',
    'text-secondary': '#696c77',
    'text-tertiary': '#a0a1a7',
    accent: '#4078f2',
    'accent-hover': '#3268d8',
    border: '#d4d4d5',
    danger: '#e45649',
    success: '#50a14f',
    warning: '#c18401',
    'scrollbar-track': '#f0f0f0',
    'scrollbar-thumb': '#d4d4d5',
    'scrollbar-thumb-hover': '#b8b8b9',
  },
  tokenRules: [
    { token: '', foreground: '383a42' },
    { token: 'string', foreground: '50a14f' },
    { token: 'number', foreground: '986801' },
    { token: 'keyword', foreground: 'a626a4' },
    { token: 'delimiter', foreground: 'a0a1a7' },
    { token: 'comment', foreground: 'a0a1a7', fontStyle: 'italic' },
    { token: 'type', foreground: 'c18401' },
    { token: 'string.key.json', foreground: 'e45649' },
    { token: 'string.value.json', foreground: '50a14f' },
    { token: 'number.json', foreground: '986801' },
    { token: 'keyword.json', foreground: '0184bc' },
  ],
  editorColors: {
    'editor.background': '#fafafa',
    'editor.foreground': '#383a42',
    'editor.lineHighlightBackground': '#f0f0f0',
    'editor.selectionBackground': '#4078f233',
    'editorCursor.foreground': '#526eff',
    'editorLineNumber.foreground': '#a0a1a7',
    'editorLineNumber.activeForeground': '#383a42',
    'editor.inactiveSelectionBackground': '#4078f21a',
    'editorIndentGuide.background': '#d4d4d566',
    'editorWidget.background': '#f0f0f0',
    'editorWidget.border': '#d4d4d5',
    'input.background': '#fafafa',
    'input.foreground': '#383a42',
    'input.border': '#d4d4d5',
    'scrollbarSlider.background': '#d4d4d566',
    'scrollbarSlider.hoverBackground': '#d4d4d599',
    'scrollbarSlider.activeBackground': '#d4d4d5cc',
  },
};

export default oneLight;
