import type { ThemeDefinition } from './types';

const oneDarkPro: ThemeDefinition = {
  id: 'one-dark-pro',
  name: 'One Dark Pro',
  type: 'dark',
  colors: {
    'bg-primary': '#282c34',
    'bg-secondary': '#21252b',
    'bg-tertiary': '#1b1d23',
    'bg-surface': '#2c313c',
    'text-primary': '#abb2bf',
    'text-secondary': '#828997',
    'text-tertiary': '#495162',
    accent: '#61afef',
    'accent-hover': '#528bff',
    border: '#3e4452',
    danger: '#e06c75',
    success: '#98c379',
    warning: '#d19a66',
    'scrollbar-track': '#282c34',
    'scrollbar-thumb': '#3e4452',
    'scrollbar-thumb-hover': '#4b5263',
  },
  tokenRules: [
    { token: '', foreground: 'abb2bf' },
    { token: 'string', foreground: '98c379' },
    { token: 'number', foreground: 'd19a66' },
    { token: 'keyword', foreground: 'c678dd' },
    { token: 'delimiter', foreground: '495162' },
    { token: 'comment', foreground: '7f848e', fontStyle: 'italic' },
    { token: 'type', foreground: 'e5c07b' },
    { token: 'string.key.json', foreground: 'e06c75' },
    { token: 'string.value.json', foreground: '98c379' },
    { token: 'number.json', foreground: 'd19a66' },
    { token: 'keyword.json', foreground: '56b6c2' },
  ],
  editorColors: {
    'editor.background': '#282c34',
    'editor.foreground': '#abb2bf',
    'editor.lineHighlightBackground': '#2c313c55',
    'editor.selectionBackground': '#67769660',
    'editorCursor.foreground': '#528bff',
    'editorLineNumber.foreground': '#495162',
    'editorLineNumber.activeForeground': '#828997',
    'editor.inactiveSelectionBackground': '#3e445233',
    'editorIndentGuide.background': '#3e445266',
    'editorWidget.background': '#21252b',
    'editorWidget.border': '#3e4452',
    'input.background': '#2c313c',
    'input.foreground': '#abb2bf',
    'input.border': '#3e4452',
    'scrollbarSlider.background': '#3e445266',
    'scrollbarSlider.hoverBackground': '#3e445299',
    'scrollbarSlider.activeBackground': '#3e4452cc',
  },
};

export default oneDarkPro;
