import type { ThemeDefinition } from './types';

const quietLight: ThemeDefinition = {
  id: 'quiet-light',
  name: 'Quiet Light',
  type: 'light',
  colors: {
    'bg-primary': '#f5f5f5',
    'bg-secondary': '#ebebeb',
    'bg-tertiary': '#e0e0e0',
    'bg-surface': '#e8e8e8',
    'text-primary': '#333333',
    'text-secondary': '#666666',
    'text-tertiary': '#999999',
    accent: '#4b83cd',
    'accent-hover': '#3a6db3',
    border: '#d1d1d1',
    danger: '#aa3731',
    success: '#448c27',
    warning: '#9c5d27',
    'scrollbar-track': '#ebebeb',
    'scrollbar-thumb': '#d1d1d1',
    'scrollbar-thumb-hover': '#b5b5b5',
  },
  tokenRules: [
    { token: '', foreground: '333333' },
    { token: 'string', foreground: '448c27' },
    { token: 'number', foreground: 'ab6526' },
    { token: 'keyword', foreground: '4b83cd' },
    { token: 'delimiter', foreground: '999999' },
    { token: 'comment', foreground: 'aaaaaa', fontStyle: 'italic' },
    { token: 'type', foreground: '7a3e9d' },
    { token: 'string.key.json', foreground: 'aa3731' },
    { token: 'string.value.json', foreground: '448c27' },
    { token: 'number.json', foreground: 'ab6526' },
    { token: 'keyword.json', foreground: '4b83cd' },
  ],
  editorColors: {
    'editor.background': '#f5f5f5',
    'editor.foreground': '#333333',
    'editor.lineHighlightBackground': '#ebebeb',
    'editor.selectionBackground': '#4b83cd33',
    'editorCursor.foreground': '#54494b',
    'editorLineNumber.foreground': '#999999',
    'editorLineNumber.activeForeground': '#333333',
    'editor.inactiveSelectionBackground': '#4b83cd1a',
    'editorIndentGuide.background': '#d1d1d166',
    'editorWidget.background': '#ebebeb',
    'editorWidget.border': '#d1d1d1',
    'input.background': '#ffffff',
    'input.foreground': '#333333',
    'input.border': '#d1d1d1',
    'scrollbarSlider.background': '#d1d1d166',
    'scrollbarSlider.hoverBackground': '#d1d1d199',
    'scrollbarSlider.activeBackground': '#d1d1d1cc',
  },
};

export default quietLight;
