import type { ThemeDefinition } from './types';

const solarizedLight: ThemeDefinition = {
  id: 'solarized-light',
  name: 'Solarized Light',
  type: 'light',
  colors: {
    'bg-primary': '#fdf6e3',
    'bg-secondary': '#eee8d5',
    'bg-tertiary': '#e0dbc8',
    'bg-surface': '#eee8d5',
    'text-primary': '#073642',
    'text-secondary': '#586e75',
    'text-tertiary': '#93a1a1',
    accent: '#268bd2',
    'accent-hover': '#1a6fb0',
    border: '#d3cbb7',
    danger: '#dc322f',
    success: '#859900',
    warning: '#b58900',
    'scrollbar-track': '#eee8d5',
    'scrollbar-thumb': '#d3cbb7',
    'scrollbar-thumb-hover': '#b8b09a',
  },
  tokenRules: [
    { token: '', foreground: '073642' },
    { token: 'string', foreground: '2aa198' },
    { token: 'number', foreground: 'd33682' },
    { token: 'keyword', foreground: '859900' },
    { token: 'delimiter', foreground: '93a1a1' },
    { token: 'comment', foreground: '93a1a1', fontStyle: 'italic' },
    { token: 'type', foreground: 'b58900' },
    { token: 'string.key.json', foreground: '268bd2' },
    { token: 'string.value.json', foreground: '2aa198' },
    { token: 'number.json', foreground: 'd33682' },
    { token: 'keyword.json', foreground: 'cb4b16' },
  ],
  editorColors: {
    'editor.background': '#fdf6e3',
    'editor.foreground': '#073642',
    'editor.lineHighlightBackground': '#eee8d5',
    'editor.selectionBackground': '#268bd233',
    'editorCursor.foreground': '#268bd2',
    'editorLineNumber.foreground': '#93a1a1',
    'editorLineNumber.activeForeground': '#586e75',
    'editor.inactiveSelectionBackground': '#268bd21a',
    'editorIndentGuide.background': '#d3cbb766',
    'editorWidget.background': '#eee8d5',
    'editorWidget.border': '#d3cbb7',
    'input.background': '#fdf6e3',
    'input.foreground': '#073642',
    'input.border': '#d3cbb7',
    'scrollbarSlider.background': '#d3cbb766',
    'scrollbarSlider.hoverBackground': '#d3cbb799',
    'scrollbarSlider.activeBackground': '#d3cbb7cc',
  },
};

export default solarizedLight;
